name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
        matrix:
            os: [ ubuntu-latest, windows-latest ]
            node-version: [ 14,15,16 ]
        # max-parallel: 3
        fail-fast: false # evita que todos los jobs posteriores se cancelen si en caso falla uno
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - run: node -v
        