name: Working Dirs & Shells
on: [push]

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
        - name: Display Working Directory & List Files
        run: |
            pwd
            ls -a